### ISSUE TITLE
I get this message in the console whenever I use this plugin

### ISSUE THREAD

**Issue by jalasem** [zamarrowski/react-ionicons#14]
Warning: You are manually calling a React.PropTypes validation function for the `style` prop on `Ionicon`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

**Comment by zamarrowski** [comment]
@jalasem thanks for feedback! 😄 
How can I reproduce that warning? What react version are you using? Usually, I use react-create-app and I can't see that error...

**Comment by zamarrowski** [comment]
Fixes in https://github.com/zamarrowski/react-ionicons/blob/9f91ed787d34096fe166580b66cdce8ecd061385/src/index.js#L71
