### ISSUE TITLE
Add support for ionicons 3

### ISSUE THREAD

**Issue by edgeadjei** [zamarrowski/react-ionicons#23]
Are there any plans to add support for [ionicons 3](https://infinitered.github.io/ionicons-version-3-search/)

**Comment by zamarrowski** [comment]
Yeah, I working in this. I hope that in the next week I have a version of react-ionicons with ionicons v3 🎉

**Comment by zamarrowski** [comment]
@edgeadjei Check out https://zamarrowski.github.io/react-ionicons/. Support for ionicons 3 is ready!
