### ISSUE TITLE
Rotate attribute error

### ISSUE THREAD

**Issue by kadjei** [zamarrowski/react-ionicons#29]
I'm receiving an error for what seems to be a bug when using the component.
Below is my component which renders just fine.

```js
<Ionicon
   fontSize="2em"
   color="white"
   icon="ios-menu"></Ionicon>
```
upon visiting my console i'm presented with the error below

```js
Warning: Received `false` for a non-boolean attribute `rotate`.

If you want to write it to the DOM, pass a string instead: rotate="false" or rotate={value.toString()}.

If you used to conditionally omit it with rotate={condition && value}, pass rotate={condition ? value : undefined} instead.
    in svg
    in styled.svg
    in Ionicon (created by Icons)
    in button (created by Icons)
    ...
```
as you can see I haven't specified the rotate attribute on my component but still receiving the above warning.

**Comment by zamarrowski** [comment]
I just published a new version: 2.1.5 that fixest this error 😄  Some people have a similar error when use styled-components: https://github.com/styled-components/styled-components/issues/1198
