### ISSUE TITLE
Feature request: get availables icon name

### ISSUE THREAD

**Issue by entraigas** [zamarrowski/react-ionicons#33]
Hi, this is a feature request.
I'm building an icon picker and just wonder if there's a way to loop through all the available icons?
something like:

```
renderIcons() {
  let retval = [];
  for(let key in iconset){
    retval.push(<Ionicon icon={key} />);
  }
  return retval;
}
```

iconset has all the available icons

**Comment by entraigas** [comment]
Nevermind just found a workaround.

**Comment by zamarrowski** [comment]
HI! I'm interested in seeing the icon-picker. Can I see it? :smile:
