### ISSUE TITLE
Applying custom CSS styles to icons don't work

### ISSUE THREAD

**Issue by anesask** [zamarrowski/react-ionicons#37]
Tried to add some custom styles as margin, padding...but I didn't manage to work...
Is it any solution to this or similar problem?

**Comment by zamarrowski** [comment]
Hi @anesask, can you paste the code to help you?
To apply custom styles just try this:
```
<Ionicon styles={{marginLeft: '10px'}} icon="md-home"/>
```

**Comment by anesask** [comment]
@zamarrowski Inline CSS styles works perfectly, but as a class I can't change font-size or color?


`<Ionicon class="someStyles" icon="md-home"/>`

`someStyles{
font-size: 14px;
color: #d4d4d4;
}`

**Comment by zamarrowski** [comment]
@anesask Yes, you can. But the correct property is fill because is a svg icon. Example:
```
.example {
  fill: red;
  height: 70px;
}
```

```
 <Ionicon className="example" icon="md-add" style={{marginRight: '8px'}} />  

```

**Comment by anesask** [comment]
> @anesask Yes, you can. But the correct property is fill because is a svg icon. Example:
> 
> ```
> .example {
>   fill: red;
>   height: 70px;
> }
> ```
> ```
>  <Ionicon className="example" icon="md-add" style={{marginRight: '8px'}} />  
> ```

Thanks a lot! Made my day easier :)
