### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by gustavengstrom** [zamarrowski/react-ionicons#39]
After installing I get the following error when testing:

import LogoNodejs from 'react-ionicons/lib/LogoNodejs'
Module not found: Can't resolve 'react-ionicons/lib/LogoNodejs'

Makes sense since when checking my local node_modules directory I am unable to locate "LogoNodejs.js".

However I did find instructions which gives me the following example:

import Ionicon from 'react-ionicons'
<Ionicon icon="ios-node-js" fontSize="20px" />

This works but screws up other css content in my App...

Any idea what I am doing wrong?

**Comment by zamarrowski** [comment]
Maybe you have another version. The doc is for ^3.0.0 version.

**Comment by gustavengstrom** [comment]
@zamarrowski I checked the installed version and you are correct the package.json file in my node_modules library said: 

  "name": "react-ionicons-docs",
  "version": "0.0.1"

Maybe either npm needs an update or you could write this in the install instructions that it needs to be:

npm install --save react-ionicons@^3.0.0

...so newbies like myself don't get confused ;)

**Comment by zamarrowski** [comment]
Good point, I need to work in a better doc and support old versions.

**Comment by merges** [comment]
@zamarrowski Can I ask why you made this breaking change in version 3.0.0? There's no documentation or rationale that I can find for those of us who've built apps using the older API (import default, use "icon" prop to specify icon). Thanks for any pointers!

**Comment by zamarrowski** [comment]
@merges I made this breaking point to import in your bundle only the icons that you use in your app. Before this change all icons were imported
