### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by andfs** [zamarrowski/react-ionicons#41]
Do you have plans to support typescript for this library? It'd be a great feature

**Comment by Flcwl** [comment]
I have same question.

**Comment by gajatko** [comment]
Bump bump. Please please.

**Comment by gino8080** [comment]
bump

**Comment by Alon-L** [comment]
Bump

**Comment by RichardLindhout** [comment]
react-app-env.d.ts
```
/// <reference types="react-scripts" />

declare module 'react-ionicons/lib/*' {
  type _a = {
    style?: CSS.Properties
    className?: any
    color?: string
    fontSize?: number
    onClick?: () => any
    rotate?: boolean
    shake?: boolean
    beat?: boolean
  }
  export = _a
}

```

**Comment by jhimelymendoza** [comment]
bump

**Comment by NTag** [comment]
In the meantime, you can create a file `react-ionicons.d.ts` containing:
```ts
type IoniconProps = {
  color?: string;
  style?: Object;
  fontSize?: string;
  rotate?: boolean;
  shake?: boolean;
  beat?: boolean;
  onClick?: (event?: Event) => void;
  children?: React.ReactNode;
};

declare module "react-ionicons/lib/*" {
  function Icon(props: IoniconProps) {
    return null;
  }

  export = Icon;
}
```

**Comment by RichardLindhout** [comment]
That looks very nice!
Since when is * supported in module names, last time I checked it did not work?

**Comment by NTag** [comment]
With my configuration (create-react-app 4 with TypeScript 4) it seems to work fine 🤷‍♂️ .

**Comment by RichardLindhout** [comment]
Great!! Tried something similar but failed, I'll try this next time I'm working on that project again <3

**Comment by RichardLindhout** [comment]
It works great <3! Had some small type errors so here are some improvements and add a missing className property

  type IoniconProps = {
    color?: string
    style?: React.CSSProperties
    fontSize?: string
    rotate?: boolean
    shake?: boolean
    className?: string
    beat?: boolean
    onClick?: (event?: Event) => void
    children?: React.ReactNode
  }

**Comment by itsgracian** [comment]
> In the meantime, you can create a file `react-ionicons.d.ts` containing:
> 
> ```ts
> type IoniconProps = {
>   color?: string;
>   style?: Object;
>   fontSize?: string;
>   rotate?: boolean;
>   shake?: boolean;
>   beat?: boolean;
>   onClick?: (event?: Event) => void;
>   children?: React.ReactNode;
> };
> 
> declare module "react-ionicons/lib/*" {
>   function Icon(props: IoniconProps) {
>     return null;
>   }
> 
>   export = Icon;
> }
> ```

Hello, Where this file should be placed. under src directory or?

**Comment by mariav7** [comment]
> > In the meantime, you can create a file `react-ionicons.d.ts` containing:
> > ```ts
> > type IoniconProps = {
> >   color?: string;
> >   style?: Object;
> >   fontSize?: string;
> >   rotate?: boolean;
> >   shake?: boolean;
> >   beat?: boolean;
> >   onClick?: (event?: Event) => void;
> >   children?: React.ReactNode;
> > };
> > 
> > declare module "react-ionicons/lib/*" {
> >   function Icon(props: IoniconProps) {
> >     return null;
> >   }
> > 
> >   export = Icon;
> > }
> > ```
> 
> Hello, Where this file should be placed. under src directory or?

I have the same question...

**Comment by zamarrowski** [comment]
Now react-ionicons@4.1.0 have typescript support. Sorry for the delay.
