### ISSUE TITLE
Import Style

### ISSUE THREAD

**Issue by Faisal-Manzer** [zamarrowski/react-ionicons#42]
The current style is good but have is lengthy to import.
```js
import IosSchool from "react-ionicons/lib/IosSchool";
```
If I had 10 icons in a component then this itself becomes cluttered. 

I suggest to change to
```js
import Icon from "react-ionicons";

...
<Icon name="ios-school" ... />
```

I know that this will make bundle larger but having this is good for large projects.

**Comment by zamarrowski** [comment]
In v2 of react-ionicons it was used like you say but I change because the bundle it was too big. Use v2 if you want.
