### ISSUE TITLE
Console Warnings Due to React Version

### ISSUE THREAD

**Issue by Xaugen** [zamarrowski/react-ionicons#45]
Hi, 

Warnings are shown when using any icon due to use of `componentWillMount` and `componentDidUpdate`. Do you have any plans for refactoring your library?

![Screen Shot 2019-11-26 at 9 58 54 AM](https://user-images.githubusercontent.com/43573843/69614512-893bde00-1033-11ea-965d-439a49944b7e.png)

Thanks.

**Comment by zamarrowski** [comment]
Thanks! In the next days I will work for use hooks instead of classes for avoid this warnings
