### ISSUE TITLE
Upgrade styled-components

### ISSUE THREAD

**Issue by makeitraina** [zamarrowski/react-ionicons#49]
Any plans on upgrading to styled-components 5.01. It is vastly faster and better than the previous major release.

**Comment by zamarrowski** [comment]
I keep in mind update styled-components version so maybe this week I will work in this! Ty!

**Comment by duncanj** [comment]
This library seems to be the best way to use ionicons with react, when you don't want the rest of the ionic framework.  I would really appreciate an upgrade to support v5 of ionicons.   Thanks!

**Comment by samandeggs** [comment]
> This library seems to be the best way to use ionicons with react, when you don't want the rest of the ionic framework. I would really appreciate an upgrade to support v5 of ionicons. Thanks!

+1 - older social media icons are a big detraction to using this in production. Instagram stands out, as they haven't used that logo in years.

**Comment by zamarrowski** [comment]
I released a new version using v5 of ionicons :)
