### ISSUE TITLE
How Can I Contribute?

### ISSUE THREAD

**Issue by christiannaths** [zamarrowski/react-ionicons#56]
@zamarrowski I'd like to help keep this package up-to-date, rather than creating my own or maintaining my own fork.

Not sure what your roadmap looks like, but if you're interested here are a few areas I'd love to discuss and possibly work on:

1. Store svg sources in the repo, create a generator to turn them into react components (to ease the workload when new Ionicons are released)
1. Update to Ionicons 5.1.2 (new icon addtions, outline, filled, and sharp styles)
1. Expand the API to create a generic `<IonIcon/>` component that takes a `name` prop, so that any icon can be used by the name as shown by ionicons.com (i.e., `<IonIcon name="arrow-forward-circle-outline" />`)
1. Consider #40 
1. Remove animations. IMO while these may be nice-to-haves, they're superfluous to the core needs of this lib.
1. Update some prop defaults; `color="currentColor"` and `fontSize="1em"`

Let me know what you think, and how I can best help.

**Comment by zamarrowski** [comment]
@christiannaths sorry for answering to late :(

I released a new version that uses ionicons 5.1.2 and create some scripts in `utils` folders to generate components but currently is so sketchy.

I will work on a documentation that explains how to contribute to this library, add linters, tests...

When we have this documentation we will know how to contribute, sorry :(

**Comment by christiannaths** [comment]
Hey, no worries at all! I know how this stuff goes sometimes. Thanks for the reply :)
