### ISSUE TITLE
Any upgrade guide from version 3?

### ISSUE THREAD

**Issue by simakwm** [zamarrowski/react-ionicons#61]
I see v4 is not backward compatible with 3. 
What should we do?

**Comment by zamarrowski** [comment]
I'm going to improve the docs and include a section explaining how to migrate from v3 to v4.
Maybe I will to create a script to automate this process so when I have the solution finished I will reference the PR to this issue

**Comment by zamarrowski** [comment]
@simakwm check out this https://react-ionicons.netlify.app/migration-v3-to-v4 😄

**Comment by simakwm** [comment]
Thanks!
